name: MainPortfolio_CDPipeline

env:
  IMAGE_NAME: devanas001/main_portfolio_cicd:latest
  
on:
  workflow_run:
    workflows: ["MainPortfolio_CIPipeline"]
    types:
      - completed

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Pull latest image
        run: docker pull $IMAGE_NAME

      - name: Remove old container
        run: docker rm -f idevanas-main-portfolio || true

      - name: Start portfolio container
        run: |
         docker run -d \
            --name idevanas-main-portfolio \
            --restart unless-stopped \
            -p 8080:80 \
            $IMAGE_NAME
